# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-13 19:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20160513_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 13, 19, 9, 15, 739908, tzinfo=utc), verbose_name='date published'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='question_text',
            field=models.CharField(default=datetime.datetime(2016, 5, 13, 19, 9, 24, 669624, tzinfo=utc), max_length=200),
            preserve_default=False,
        ),
    ]
